RADAR-base/radar-upload-source-connector

integration-test/build.gradle.kts, integration-test/src/integrationTest/java/org/radarbase/connect/upload/api/UploadBackendClientIntegrationTest.kt, radar-upload-backend/build.gradle.kts, radar-upload-backend/src/main/java/org/radarbase/upload/Config.kt, radar-upload-backend/src/main/java/org/radarbase/upload/auth/Auth.kt, radar-upload-backend/src/main/java/org/radarbase/upload/auth/MPClient.kt, radar-upload-backend/src/main/java/org/radarbase/upload/auth/ManagementPortalAuth.kt, radar-upload-backend/src/main/java/org/radarbase/upload/auth/NeedsPermissionOnProject.kt, radar-upload-backend/src/main/java/org/radarbase/upload/auth/NeedsPermissionOnUser.kt, radar-upload-backend/src/main/java/org/radarbase/upload/doa/RecordRepositoryImpl.kt, radar-upload-backend/src/main/java/org/radarbase/upload/dto/Project.kt, radar-upload-backend/src/main/java/org/radarbase/upload/dto/QueuedCallbackManager.kt, radar-upload-backend/src/main/java/org/radarbase/upload/exception/BadGatewayException.kt, radar-upload-backend/src/main/java/org/radarbase/upload/exception/ConflictException.kt, radar-upload-backend/src/main/java/org/radarbase/upload/exception/HttpApplicationException.kt, radar-upload-backend/src/main/java/org/radarbase/upload/exception/HttpApplicationExceptionMapper.kt, radar-upload-backend/src/main/java/org/radarbase/upload/exception/NotAuthorizedException.kt, radar-upload-backend/src/main/java/org/radarbase/upload/exception/NotFoundException.kt, radar-upload-backend/src/main/java/org/radarbase/upload/filter/PermissionFilter.kt, radar-upload-backend/src/main/java/org/radarbase/upload/inject/AuthorizationFeature.kt, radar-upload-backend/src/main/java/org/radarbase/upload/inject/UploadResourceConfig.kt, radar-upload-backend/src/main/java/org/radarbase/upload/resource/ProjectResource.kt, radar-upload-backend/src/main/java/org/radarbase/upload/resource/RecordResource.kt, radar-upload-backend/src/main/java/org/radarbase/upload/service/MPService.kt, radar-upload-backend/src/main/java/org/radarbase/upload/util/CachedSet.kt
Adds the following calls to the backend:
GET `/projects`
```json
{
"projects": [{
"id": "test",
"name": "Test",
"location": "Utrecht",
"organization": "The Hyve",
"description": "my test project"
}]
}
```
GET `/projects/{projectId}/users`
```json
{
"users": [{
"id": "abcdef",
"projectId": "test",
"externalId": "AB10",
"status": "ACTIVATED"
}]
}
```
=> Add a project and user listing

radar-upload-backend/build.gradle.kts, radar-upload-backend/src/main/java/org/radarbase/upload/api/RecordMapperImpl.kt, radar-upload-backend/src/test/java/org/radarbase/upload/api/RecordMapperImplTest.kt
Improve handling of filenames with symbols. Fixes #16 and #17.
=> Fixes response on filenames with weird characters

radar-upload-backend/src/main/java/org/radarbase/upload/auth/Auth.kt, radar-upload-backend/src/main/java/org/radarbase/upload/auth/ManagementPortalAuth.kt, radar-upload-backend/src/main/java/org/radarbase/upload/resource/LoginResource.kt
For completeness, added a resource to remove the authenticationBearer cookie.
=> Log out API

radar-upload-backend/src/main/java/org/radarbase/upload/api/ApiDeclarations.kt, radar-upload-backend/src/main/java/org/radarbase/upload/api/RecordMapperImpl.kt
=> add lastId to records query response

radar-upload-frontend/src/components/Login/index.vue
Make login from ManagementPortal explicit #32
=> Make login from ManagementPortal explicit #32

radar-upload-frontend/src/axios/__tests__/file.spec.js, radar-upload-frontend/src/axios/file.js, radar-upload-frontend/src/components/Common/UploadForm.vue, radar-upload-frontend/src/components/Common/__tests__/UploadForm.spec.js
markRecord after uploading file #24
=> add markRequest after uploading file #24

radar-upload-frontend/src/components/Patient/PatientTable/__tests__/index.spec.js, radar-upload-frontend/src/components/Patient/PatientTable/index.vue
Make the whole participant row click-able 
Fixes #52
=> Make the whole participant row click-able #52

radar-upload-frontend/src/App.vue, radar-upload-frontend/src/components/Project/ProjectList.vue, radar-upload-frontend/src/components/Project/__tests__/ProjectList.spec.js, radar-upload-frontend/src/components/Project/__tests__/projectMixin.spec.js, radar-upload-frontend/src/components/Project/projectMixin.js, radar-upload-frontend/src/router.js, radar-upload-frontend/src/views/contents/PatientFileTabs.vue, radar-upload-frontend/src/views/contents/__tests__/PatientFileTabs.spec.js
Add project-id to the route when opening a project-view 
Fixes #31
=> Add project-id to the route when opening a project-view #31

docker-compose.yml, docker/source-upload.properties, integration-test/src/integrationTest/java/org/radarbase/connect/upload/UploadSourceTaskTest.kt, integration-test/src/integrationTest/java/org/radarbase/connect/upload/util/TestBase.kt, kafka-connect-upload-source/src/main/java/org/radarbase/connect/upload/UploadSourceTask.kt
- Complete polling and return value
- modified polling
- add few more test cases
=> Modified polling

kafka-connect-upload-source/src/main/java/org/radarbase/connect/upload/converter/ConverterLogRepository.kt
=> Thread safe log container

integration-test/src/integrationTest/java/org/radarbase/connect/upload/UploadSourceTaskTest.kt, integration-test/src/integrationTest/java/org/radarbase/connect/upload/api/UploadBackendClientIntegrationTest.kt, kafka-connect-upload-source/src/main/java/org/radarbase/connect/upload/UploadSourceTask.kt, radar-upload-backend/src/main/java/org/radarbase/upload/auth/MPClient.kt, radar-upload-backend/src/main/java/org/radarbase/upload/doa/RecordRepository.kt, radar-upload-backend/src/main/java/org/radarbase/upload/doa/RecordRepositoryImpl.kt, radar-upload-backend/src/main/java/org/radarbase/upload/resource/RecordResource.kt, upload.yml
Adds additional query paramteres for records and polling
- Adds `status` and `sourceType` query parameters to `GET records/`
- Implements `supportedConverters` when polling for records
Fixes #38 
Fixes #39
=> Api improvements

radar-upload-backend/src/main/java/org/radarbase/upload/resource/ProjectResource.kt, radar-upload-backend/src/main/java/org/radarbase/upload/service/MPService.kt
Adds an endpoint to get project by name. This api was requested by @khoathanglong while ago.
=> add querying a project by project-name api

radar-upload-backend/src/main/java/org/radarbase/upload/resource/RecordResource.kt
Should fix #75.
- Handles `IOException` in streaming output.
- Checks that logs exist before streaming them.
=> Better handling if streaming output is interrupted

radar-upload-frontend/src/components/Common/UploadForm.vue, radar-upload-frontend/src/components/Common/__tests__/UploadForm.spec.js, radar-upload-frontend/src/components/Patient/PatientTable/UploadButton.vue, radar-upload-frontend/src/components/Patient/PatientTable/__tests__/index.spec.js, radar-upload-frontend/src/components/Patient/PatientTable/index.vue
update record status after mark ready #51
=> Fe upload file

docs/README.md, radar-upload-backend/src/main/java/org/radarbase/upload/api/ApiDeclarations.kt, radar-upload-backend/src/main/java/org/radarbase/upload/api/RecordMapper.kt, radar-upload-backend/src/main/java/org/radarbase/upload/api/RecordMapperImpl.kt, radar-upload-backend/src/main/java/org/radarbase/upload/doa/RecordRepository.kt, radar-upload-backend/src/main/java/org/radarbase/upload/doa/RecordRepositoryImpl.kt, radar-upload-backend/src/main/java/org/radarbase/upload/resource/RecordResource.kt
Adds support to pagination to records. Pagination support for participants should still be implemented. For now we should list all participants. 
Partially solves #29
=> Pagination support for records

radar-upload-backend/src/main/java/org/radarbase/upload/Config.kt, radar-upload-backend/src/main/java/org/radarbase/upload/api/ApiDeclarations.kt, radar-upload-backend/src/main/java/org/radarbase/upload/api/RecordMapperImpl.kt, radar-upload-backend/src/main/java/org/radarbase/upload/service/UploadProjectService.kt, radar-upload-backend/src/main/java/org/radarbase/upload/service/managementportal/MPProjectService.kt, radar-upload-backend/src/test/java/org/radarbase/upload/api/RecordMapperImplTest.kt, radar-upload-backend/src/test/java/org/radarbase/upload/mock/MockProjectService.kt, radar-upload-backend/src/test/java/org/radarbase/upload/mock/MockResourceEnhancerFactory.kt, radar-upload-backend/src/test/java/org/radarbase/upload/resource/RecordResourceTest.kt
support record creation with externalUserId
add variables to configure intervals to sync with MP
Fixes #98
=> support record creation with externalUserId

integration-test/docker-compose.yml, integration-test/src/integrationTest/java/org/radarbase/connect/upload/util/TestBase.kt, radar-upload-backend/src/main/java/org/radarbase/upload/api/RecordMapperImpl.kt, radar-upload-backend/src/main/java/org/radarbase/upload/resource/RecordResource.kt, radar-upload-backend/src/main/java/org/radarbase/upload/service/managementportal/MPProjectService.kt, radar-upload-backend/src/test/java/org/radarbase/upload/resource/RecordResourceTest.kt, radar-upload-frontend/src/axios/__tests__/file.spec.js, radar-upload-frontend/src/axios/file.js, radar-upload-frontend/src/components/Upload/UploadForm.vue, radar-upload-frontend/src/components/Upload/__tests__/UploadForm.spec.js
- Adds check for content-type and content-length headers Fixes #17 
- checks for existence of project Id and user Id or externalized Related to #98 
- Adds default content type from front-end #110
=> Minor fixes

kafka-connect-upload-source/src/main/java/org/radarbase/connect/upload/converter/altoida/AltoidaConverterFactory.kt, kafka-connect-upload-source/src/main/java/org/radarbase/connect/upload/converter/altoida/AltoidaMagneticFieldCsvProcessor.kt
=> hotfix for mismatch in topic name

kafka-connect-upload-source/src/main/java/org/radarbase/connect/upload/converter/RecordConverter.kt
It is rather a strange issue. Given the time constraints and priorities, I am proceeding with this suggested fix/workaround.
Fixes #120
=> Hotfix for seriablizing camera data

kafka-connect-upload-source/src/main/java/org/radarbase/connect/upload/converter/altoida/AltoidaTouchScreenCsvProcessor.kt
=> hotfix: fix altoida touch with correct topic

kafka-connect-upload-source/src/main/java/org/radarbase/connect/upload/converter/axivity/newcastle/CwaBlock.java
I did a small review of the CWA block processing, with some edits for readability.
=> Some readability updates for axivity

radar-upload-backend/src/main/java/org/radarbase/upload/api/RecordMapperImpl.kt
=> fix having records with empty UserId

README.md, kafka-connect-upload-source/src/main/java/org/radarbase/connect/upload/converter/oxford/CameraUploadProcessor.kt, kafka-connect-upload-source/src/main/java/org/radarbase/connect/upload/converter/oxford/WearableCameraConverterFactory.kt, kafka-connect-upload-source/src/main/java/org/radarbase/connect/upload/io/LocalFileUploader.kt
Added a local file uploader, if the connector does not connect to SFTP but uploads files directly to the local files system.
=> Add possibility for local wearable data upload

kafka-connect-upload-source/src/main/java/org/radarbase/connect/upload/converter/oxford/WearableCameraConverterFactory.kt
ignore ACTIVITY.CSV file from wearable camera data. (no knowledge on the content)
=> Fix wearable data structure

README.md, build.gradle.kts, docker-compose.yml
=> Release 0.4.1

radar-upload-backend/src/main/java/org/radarbase/upload/service/managementportal/MPClient.kt
fix missing query params to get full list of data
=> fix missing query params to get full list of data

build.gradle.kts, kafka-connect-upload-source/build.gradle.kts, kafka-connect-upload-source/src/main/java/org/radarbase/connect/upload/converter/axivity/EventsCwaBlockProcessor.kt
**Changes from release 0.5.5.1**
- Fixes connector build for java
=> Release 0.5.5.2

radar-upload-backend/src/main/java/org/radarbase/upload/doa/RecordRepositoryImpl.kt, radar-upload-backend/src/main/java/org/radarbase/upload/resource/RecordResource.kt, radar-upload-frontend/src/axios/file.js, radar-upload-frontend/src/components/Record/RecordTable.vue
- Adds retry feature which essentially resets/updates the `RecordMetaData` status to `READY`
Solves #165
=> Add retry feature for records

radar-upload-backend/Dockerfile
- Fix Dockerfile (release GA failing)
=> Fix Dockerfile

.github/workflows/scheduled-snyk-docker.yaml, .github/workflows/scheduled-snyk.yaml, .github/workflows/snyk.yaml
=> Add weekly Snyk Docker image scan to Github actions

radar-upload-frontend/Dockerfile, radar-upload-frontend/docker/entrypoint.sh, radar-upload-frontend/docker/nginx.conf
Nginx will run now as a normal user and is able to run even if the root directory is set as read only.
=> Improved security of the frontend Docker image

build.gradle.kts, buildSrc/src/main/kotlin/Versions.kt, kafka-connect-upload-source/Dockerfile, radar-upload-backend/Dockerfile
=> Apply security upgrades March 2025 platform upgrade

build.gradle.kts, radar-upload-frontend/Dockerfile, radar-upload-frontend/package-lock.json, radar-upload-frontend/package.json
=> Up project version to 0.5.15
